markdown: rdiscount
highlighter: rouge
permalink: /:year/:month/:day/:title.html
name: "Paradox"
markdown: rdiscount

author: "yu liu"
atom-baseurl: ""
disqus: "gopherwood"

navigations:
  - title: Home
    class: fa fa-home
    href: /
  - title: Archive
    class: fa fa-list
    href: /archive.html
  - title: Categories
    class: fa fa-book
    href: /categories.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: Search
    class: fa fa-search
    href: /search.html
  - title: About
    class: fa fa-user
    href: /about.html
  - title: Gallery
    class: fa fa-film
    href: /placeholder.html
  - title: Link
    class: fa fa-external-link
    href: /links.html
  - title: Subscribe
    class: fa fa-rss
    href: /atom.xml

